## Numpy

In [7]:
import numpy as np

### zeros : 0으로 채워진 numpy array 생성

In [3]:
zeros = np.zeros([3, 3])
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [6]:
zeros = np.zeros(1)
zeros

array([0.])

### ones : 1로 채워진 numpy array 생성

In [8]:
ones = np.ones([10, 5])
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [9]:
ones * 5

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

### arange : O ~ O 범위의 숫자를 가지는 numpy array 생성

In [10]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [15]:
arr = np.arange(4, 9)
arr

array([4, 5, 6, 7, 8])

처음 생성은 1차원 -> reshape를 통해 차원 변경 가능

In [16]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### index : list에서 index로 값에 접근하듯이 numpy도 index를 통해 값 접근 가능

In [17]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [18]:
arr[0]

array([0, 1, 2])

numpy는 arr[0][1] 과 arr[0, 1]이 같은 결과를 갖게됨

In [19]:
arr[0][1]

1

In [21]:
arr[0, 1]

1

### Slicing

In [22]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [23]:
arr[1:]

array([[3, 4, 5],
       [6, 7, 8]])

두번째 행부터 그 해당하는 행의 두번째 열의 값부터

In [24]:
arr[1:, 1:]

array([[4, 5],
       [7, 8]])

### Boolean Indexing

In [26]:
data = np.random.randn(3, 3)
data

array([[ 1.05163872, -0.49916459,  1.70255328],
       [ 0.69016921, -0.40783219, -0.38819247],
       [ 1.46955666,  2.36692201,  2.19415191]])

data <= 0 이라고 하면 각각의 위치의 값들과 비교하여 True, False 값으로 보여줌

In [27]:
data <= 0

array([[False,  True, False],
       [False,  True,  True],
       [False, False, False]])

data <= 0 을 조건으로 해서 해당하는 값을 = 1 로 수정 가능

In [28]:
data[data<=0] = 1
data

array([[1.05163872, 1.        , 1.70255328],
       [0.69016921, 1.        , 1.        ],
       [1.46955666, 2.36692201, 2.19415191]])

### Broadcast

#### 연산하려는 서로 다른 두개의 행렬의 shape가 같지 않고 한쪽의 차원이라도 같거나 값의 갯수가 한개일 때 이를 여러개로 복사를 하여 연산을 함

In [36]:
arr = np.arange(9).reshape(3, 3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [30]:
arr + 3

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [31]:
arr * 3

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24]])

In [38]:
arr + np.array([1, 2, 3])

array([[ 1,  3,  5],
       [ 4,  6,  8],
       [ 7,  9, 11]])

---

### 수학적 연산

In [50]:
arr = np.arange(9).reshape(3, 3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### arr + 10 == np.add(arr, 10)

In [51]:
arr + 10

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [52]:
np.add(arr, 10)

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

#### arr * 5 == np.multiply(arr, 5)

In [53]:
arr * 5

array([[ 0,  5, 10],
       [15, 20, 25],
       [30, 35, 40]])

In [54]:
np.multiply(arr, 5)

array([[ 0,  5, 10],
       [15, 20, 25],
       [30, 35, 40]])

In [55]:
arr + arr

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

#### 랜덤인 0과 1로 이루어진 size가 27인 numpy array를 만들고 3, 3, 3 으로 reshape

In [56]:
arr = np.random.randint(2, size=27).reshape(3, 3, 3)
arr

array([[[0, 1, 1],
        [0, 0, 0],
        [0, 0, 1]],

       [[0, 1, 0],
        [1, 0, 1],
        [1, 1, 1]],

       [[1, 0, 0],
        [0, 0, 0],
        [0, 1, 0]]])

In [57]:
arr_2 = np.random.randint(2, size=9).reshape(3, 3)
arr_2

array([[0, 1, 0],
       [0, 0, 1],
       [1, 0, 0]])

In [58]:
arr.shape, arr_2.shape

((3, 3, 3), (3, 3))

In [60]:
arr + arr_2

array([[[0, 2, 1],
        [0, 0, 1],
        [1, 0, 1]],

       [[0, 2, 0],
        [1, 0, 2],
        [2, 1, 1]],

       [[1, 1, 0],
        [0, 0, 1],
        [1, 1, 0]]])

In [61]:
arr * arr_2

array([[[0, 1, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 1, 0],
        [0, 0, 1],
        [1, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

### Sum

In [64]:
np.sum(arr)

11

In [65]:
np.sum(arr + arr_2)

20

### max

In [68]:
arr + arr_2

array([[[0, 2, 1],
        [0, 0, 1],
        [1, 0, 1]],

       [[0, 2, 0],
        [1, 0, 2],
        [2, 1, 1]],

       [[1, 1, 0],
        [0, 0, 1],
        [1, 1, 0]]])

#### 그냥 max를 하면 모든 값들 중 가장 큰 값

In [66]:
np.max(arr + arr_2)

2

#### 차원에 대한 조건을 주면 각 차원별로 더한 값들로 결과를 보여줌

#### 0을 주면 각각 0차원에서 가장 큰 값
세로로 0, 0, 1 중 큰 것 2, 2, 1 중 큰 것

In [69]:
np.max(arr + arr_2, 0)

array([[1, 2, 1],
       [1, 0, 2],
       [2, 1, 1]])

#### -1을 주면 3차원에서 가장 큰 값
가로로 [0, 2, 1] 중에 가장 큰 값 / [0, 0, 1] 중에 가장 큰 값

In [70]:
np.max(arr + arr_2, -1)

array([[2, 1, 1],
       [2, 2, 2],
       [1, 1, 1]])

axis=-1 과 같은 결과

In [71]:
np.max(arr + arr_2, axis=-1)

array([[2, 1, 1],
       [2, 2, 2],
       [1, 1, 1]])

### min

In [67]:
np.min(arr + arr_2)

0

### mean : 평균 값

In [72]:
np.mean(arr)

0.4074074074074074

### argmax : 가장 큰 값이 존재하는 위치의 index 알려주기

In [73]:
arr = np.array([1, 6, 3, 7, 3, 2, 9])
arr

array([1, 6, 3, 7, 3, 2, 9])

In [74]:
np.argmax(arr)

6

### argmin : 가장 작은 값이 존재하는 위치의 index 알려주기

In [75]:
np.argmin(arr)

0

### unique : 유니크 한 값들만 뽑아줌

In [77]:
arr = np.array([3, 5, 6, 6, 3, 3, 1])
arr

array([3, 5, 6, 6, 3, 3, 1])

In [78]:
np.unique(arr)

array([1, 3, 5, 6])