## TensorFlow 2.0 간단 사용법

In [1]:
import numpy as np
import tensorflow as tf

### Tensor 생성

- tf.constant() : list, tuple, Array를 Tensor로 바꾸어줌

In [2]:
tf.constant([1, 2, 3])

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [4]:
tf.constant(((1, 2, 3), (1, 2, 3)))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [1, 2, 3]], dtype=int32)>

In [5]:
arr = np.array([ 1, 2, 3 ])
arr

array([1, 2, 3])

In [6]:
tf.constant(arr)

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([1, 2, 3])>

In [7]:
tensor = tf.constant(arr)
tensor

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([1, 2, 3])>

---

### Tensor에 담긴 정보 확인

- shape 확인

In [8]:
tensor.shape

TensorShape([3])

- data type 정의

In [11]:
tensor = tf.constant([1, 2, 3], dtype=tf.float32)
tensor

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

- data type 확인 : dtype

In [12]:
tensor.dtype

tf.float32

- data type 변환 : Numpy의 astype( ) 처럼 TensorFlow에서는 tf.cast( ) 를 활용

In [13]:
tf.cast(tensor, dtype=tf.int32)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [14]:
tensor

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

- tensor에서 Numpy 불러오기 : np.array( ) / .numpy( ) 활용

In [15]:
np.array(tensor)

array([1., 2., 3.], dtype=float32)

In [16]:
tensor.numpy()

array([1., 2., 3.], dtype=float32)

---

### 난수 생성

- Normal Distribution : tf.random.normal == np.random.randn
- Uniform Distribution : tf.random.uniform

In [17]:
tf.random.normal([3, 3])

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-2.0487728 ,  0.6003536 ,  0.11923807],
       [-0.17404579, -1.1506113 ,  0.84336704],
       [ 0.30083656,  0.95827097,  0.90375173]], dtype=float32)>

In [19]:
tf.random.uniform([3, 3])

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.2103771 , 0.18460417, 0.54693496],
       [0.3190844 , 0.57180023, 0.70573115],
       [0.40603685, 0.58343196, 0.538077  ]], dtype=float32)>